# SPDX-FileCopyrightText: (C) 2019-2025 Matthias Fehring <https://www.huessenbergnetz.de>
# SPDX-License-Identifier: LGPL-3.0-or-later

name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        build_type:
          - Debug
          - Release
        config:
          - qt_version: "5.15.*"
          - qt_version: "6.5.*"
          - qt_version: "6.8.*"

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y mariadb-server postgresql

      - name: Install Qt with options and default aqtversion
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: null  # use whatever the default is
          version: ${{ matrix.config.qt_version }}
          cache: true

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure project
        run: >
          cmake -S . -B ./build -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DENABLE_TESTS:BOOL=ON

      - name: Build project
        run: cmake --build ./build

      - name: Run tests
        id: ctest
        if: ${{ matrix.build_type == 'Debug' }}
        run: ctest --test-dir ./build -C ${{ matrix.build_type }} --output-on-failure

      - name: Read tests log when it fails
        uses: andstor/file-reader-action@v1
        if: ${{ failure() && steps.ctest.conclusion == 'failure' }}
        with:
          path: "./build/Testing/Temporary/LastTest.log"
